name: NanoRange CI

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: "Linux clang_libstdcxx Debug"
            artifact: "Linux.tar.xz"
            os: ubuntu-20.04
            build_type: Debug

          - name: "Linux clang_libstdcxx Release"
            artifact: "Linux.tar.xz"
            os: ubuntu-20.04
            build_type: Release
        compiler:
          - cc: clang
            cxx: clang++
    steps:
      - name: Install tools
        id: install_tools
        run: |
          sudo wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
          sudo apt-add-repository 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal main'
          sudo apt-get update
          sudo apt-get autoremove -y
          sudo apt-get install -y cmake g++ ninja-build clang clang-12
          clang++ --version

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure
        id: configure
        run:
          cmake . -GNinja
            -DCMAKE_C_COMPILER=${{ matrix.compiler.cc }}
            -DCMAKE_CXX_COMPILER=${{ matrix.compiler.cxx }}
            -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }}
            -DCMAKE_CXX_STANDARD=20

      - name: Build
        id: build
        run: ninja

      - name: Test
        id: test
        run: ctest -j$(nproc) --output-on-failure
